# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35e1674deffd29fbf7c83a1d909ac4634d3ada8c03b1e883432313db49eb4c03ba21f74165e678d4f66f0fe7124c998edfe002496f204626e8fa6392a4d05cf2

test:
  secret_key_base: c2680a70d4749bb2bfe14d07bde204bbd231ce6c4adfb5006a339423842aeea26c90c052e7f303d643a6bf9d15b187ad154f9c1037550044d3e9f3d456e80d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
